// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkkoepjiwdlchkkrvmub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtra29lcGppd2RsY2hra3J2bXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTk1NjMsImV4cCI6MjA2MDk5NTU2M30.0UwwVaa6N6OD8RlYdCiE6-stPqgeUrPjVO2kZOrCJaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});